name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout (push/merge)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Checkout (PR head)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build (Nix flake)
        run: nix build -L --impure
        env:
          NIXPKGS_ALLOW_UNFREE: 1

      - name: Copy book
        run: cp result/share/book.pdf ./book.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: book.pdf
          path: book.pdf
          if-no-files-found: error
          retention-days: 90
